# Generated by Django 3.1 on 2020-08-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20200821_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view_count',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
